export const HOME_VIEW = {
  position: [0, 120, 280],
  target: [0, 0, 0],
}

export const PLANET_CONFIG = [
  {
    id: 'Mercury',
    radius: 1.2,
    orbitRadius: 16,
    orbitSpeed: 0.95,
    rotationSpeed: 1.3,
    axialTilt: 0.03,
    surfaceColors: ['#9f8e77', '#564d45'],
    glowColor: '#c7b49d',
  },
  {
    id: 'Venus',
    radius: 1.8,
    orbitRadius: 24,
    orbitSpeed: 0.75,
    rotationSpeed: 0.8,
    axialTilt: 0.06,
    surfaceColors: ['#d4ae7f', '#7a5b3f'],
    atmosphereColor: '#ffd7a8',
    glowColor: '#f5cda4',
  },
  {
    id: 'Earth',
    radius: 2,
    orbitRadius: 33,
    orbitSpeed: 0.62,
    rotationSpeed: 1.8,
    axialTilt: 0.41,
    surfaceColors: ['#2d72c7', '#173a73'],
    cloudLayer: {
      colors: ['#ffffff', '#8baad8'],
      opacity: 0.36,
      speedMultiplier: 1.14,
    },
    atmosphereColor: '#69a6ff',
    glowColor: '#6ec7ff',
    moons: [
      {
        id: 'Moon',
        radius: 0.55,
        orbitRadius: 4.4,
        orbitSpeed: 2.4,
        rotationSpeed: 0.5,
        surfaceColors: ['#cfcfca', '#6f6f6b'],
        glowColor: '#d5d5d5',
      },
    ],
  },
  {
    id: 'Mars',
    radius: 1.6,
    orbitRadius: 42,
    orbitSpeed: 0.5,
    rotationSpeed: 1.45,
    axialTilt: 0.44,
    surfaceColors: ['#cb7149', '#6f341f'],
    atmosphereColor: '#ff9a7a',
    glowColor: '#db8d6d',
  },
  {
    id: 'Jupiter',
    radius: 4.4,
    orbitRadius: 58,
    orbitSpeed: 0.28,
    rotationSpeed: 2.6,
    axialTilt: 0.05,
    surfaceColors: ['#d9b78e', '#876041'],
    glowColor: '#f6d3ad',
  },
  {
    id: 'Saturn',
    radius: 3.9,
    orbitRadius: 74,
    orbitSpeed: 0.22,
    rotationSpeed: 2.1,
    axialTilt: 0.47,
    surfaceColors: ['#dcc49f', '#8f7148'],
    glowColor: '#f8dfbe',
    ring: {
      innerMultiplier: 1.45,
      outerMultiplier: 2.35,
      color: '#f2d3a2',
      opacity: 0.8,
    },
  },
  {
    id: 'Uranus',
    radius: 3.2,
    orbitRadius: 89,
    orbitSpeed: 0.16,
    rotationSpeed: 1.95,
    axialTilt: 1.7,
    surfaceColors: ['#9ddfea', '#4e8087'],
    glowColor: '#a7f3ff',
  },
  {
    id: 'Neptune',
    radius: 3.1,
    orbitRadius: 103,
    orbitSpeed: 0.12,
    rotationSpeed: 1.85,
    axialTilt: 0.49,
    surfaceColors: ['#4967d0', '#203066'],
    glowColor: '#8ea7ff',
  },
]

export const SPACECRAFT_CONFIG = {
  id: 'Voyager',
  orbitRadius: 118,
  orbitSpeed: 0.07,
}
