export const HOME_VIEW = {
  position: [0, 120, 280],
  target: [0, 0, 0],
}

export const PLANET_CONFIG = [
  {
    id: 'Mercury',
    radius: 1.2,
    orbitRadius: 16,
    orbitSpeed: 0.95,
    rotationSpeed: 1.3,
    axialTilt: 0.03,
    surfaceColors: ['#9f8e77', '#564d45'],
    glowColor: '#c7b49d',
    textures: {
      map: '/textures/planets/mercurymap.jpg',
      bumpMap: '/textures/planets/mercurybump.jpg',
      bumpScale: 0.08,
      roughness: 0.95,
      metalness: 0.04,
    },
  },
  {
    id: 'Venus',
    radius: 1.8,
    orbitRadius: 24,
    orbitSpeed: 0.75,
    rotationSpeed: 0.8,
    axialTilt: 0.06,
    surfaceColors: ['#d4ae7f', '#7a5b3f'],
    atmosphere: {
      color: '#ffd7a8',
      opacity: 0.12,
      scale: 1.035,
    },
    glowColor: '#f5cda4',
    textures: {
      map: '/textures/planets/venusmap.jpg',
      bumpMap: '/textures/planets/venusbump.jpg',
      bumpScale: 0.03,
      roughness: 0.92,
      metalness: 0.03,
    },
  },
  {
    id: 'Earth',
    radius: 2,
    orbitRadius: 33,
    orbitSpeed: 0.62,
    rotationSpeed: 1.8,
    axialTilt: 0.41,
    surfaceColors: ['#2d72c7', '#173a73'],
    cloudLayer: {
      map: '/textures/planets/earth_clouds_1024.png',
      opacity: 0.28,
      speedMultiplier: 1.14,
    },
    atmosphere: {
      color: '#69a6ff',
      opacity: 0.16,
      scale: 1.045,
    },
    glowColor: '#6ec7ff',
    textures: {
      map: '/textures/planets/earth_day_4096.jpg',
      normalMap: '/textures/planets/earth_normal_2048.jpg',
      roughnessMap: '/textures/planets/earth_bump_roughness_clouds_4096.jpg',
      bumpMap: '/textures/planets/earth_bump_roughness_clouds_4096.jpg',
      bumpScale: 0.04,
      roughness: 0.8,
      metalness: 0.02,
      emissiveMap: '/textures/planets/earth_lights_2048.png',
      emissiveColor: '#9bc4ff',
      emissiveIntensity: 0.28,
    },
    moons: [
      {
        id: 'Moon',
        radius: 0.55,
        orbitRadius: 4.4,
        orbitSpeed: 2.4,
        rotationSpeed: 0.5,
        surfaceColors: ['#cfcfca', '#6f6f6b'],
        glowColor: '#d5d5d5',
        textures: {
          map: '/textures/planets/moon_1024.jpg',
          roughness: 0.96,
          metalness: 0.02,
        },
      },
    ],
  },
  {
    id: 'Mars',
    radius: 1.6,
    orbitRadius: 42,
    orbitSpeed: 0.5,
    rotationSpeed: 1.45,
    axialTilt: 0.44,
    surfaceColors: ['#cb7149', '#6f341f'],
    atmosphere: {
      color: '#ff9a7a',
      opacity: 0.07,
      scale: 1.02,
    },
    glowColor: '#db8d6d',
    textures: {
      map: '/textures/planets/marsmap1k.jpg',
      bumpMap: '/textures/planets/marsbump1k.jpg',
      bumpScale: 0.05,
      roughness: 0.91,
      metalness: 0.03,
    },
  },
  {
    id: 'Jupiter',
    isGasGiant: true,
    radius: 4.4,
    orbitRadius: 58,
    orbitSpeed: 0.28,
    rotationSpeed: 2.6,
    axialTilt: 0.05,
    surfaceColors: ['#d9b78e', '#876041'],
    glowColor: '#f6d3ad',
    textures: {
      map: '/textures/planets/jupitermap.jpg',
      roughness: 0.62,
      metalness: 0.02,
    },
  },
  {
    id: 'Saturn',
    isGasGiant: true,
    radius: 3.9,
    orbitRadius: 74,
    orbitSpeed: 0.22,
    rotationSpeed: 2.1,
    axialTilt: 0.47,
    surfaceColors: ['#dcc49f', '#8f7148'],
    glowColor: '#f8dfbe',
    textures: {
      map: '/textures/planets/saturnmap.jpg',
      roughness: 0.67,
      metalness: 0.02,
    },
    ring: {
      innerMultiplier: 1.45,
      outerMultiplier: 2.35,
      color: '#f2d3a2',
      opacity: 0.92,
      map: '/textures/planets/saturnringcolor.jpg',
      alphaMap: '/textures/planets/saturnringpattern.gif',
      tilt: 0.08,
    },
  },
  {
    id: 'Uranus',
    isGasGiant: true,
    radius: 3.2,
    orbitRadius: 89,
    orbitSpeed: 0.16,
    rotationSpeed: 1.95,
    axialTilt: 1.7,
    surfaceColors: ['#9ddfea', '#4e8087'],
    glowColor: '#a7f3ff',
    textures: {
      map: '/textures/planets/uranusmap.jpg',
      roughness: 0.6,
      metalness: 0.02,
    },
  },
  {
    id: 'Neptune',
    isGasGiant: true,
    radius: 3.1,
    orbitRadius: 103,
    orbitSpeed: 0.12,
    rotationSpeed: 1.85,
    axialTilt: 0.49,
    surfaceColors: ['#4967d0', '#203066'],
    glowColor: '#8ea7ff',
    textures: {
      map: '/textures/planets/neptunemap.jpg',
      roughness: 0.58,
      metalness: 0.02,
    },
  },
]

export const SPACECRAFT_CONFIG = {
  id: 'Voyager',
  orbitRadius: 118,
  orbitSpeed: 0.07,
}
